### ISSUE TITLE
HotSecondsTransformer.java死锁

### ISSUE THREAD

**Issue by bd7xzzxyz** [thanple/HotSecondsIDEA#6]
1.8.0_181、1.8.0_202下都出现死锁。tomcat8 ParallelWebappClassLoader类加载器。使用的HotSecondsServer-beat，日志中同时会警告，无法加载hot-seconds-remote.xml。求问如何解决？
 WARNING Invalid javaagent option 'hotconf'. Argument 'hotconf=/opt/tomcat/webapps/ROOT/WEB-INF/classes/hot-seconds-remote.xml' is ignored.

Java stack information for the threads listed above:
===================================================
"Thread-8":
        at com.liubs.hotdeployseconds.server.HotSecondsTransformer.transform(HotSecondsTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.lang.invoke.LambdaForm$DMH/1966250569.invokeSpecial_L3IIL_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/257608164.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$MH/1237550792.invoker(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/1259652483.invokeExact_MT(LambdaForm$MH)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.hotswap.agent.javassist.util.proxy.DefineClassHelper$Java7.defineClass(DefineClassHelper.java:177)
        at org.hotswap.agent.javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:263)
        at org.hotswap.agent.javassist.ClassPool.toClass(ClassPool.java:1232)
        at org.hotswap.agent.javassist.CtClass.toClass(CtClass.java:1398)
        at org.hotswap.agent.util.classloader.ClassLoaderDefineClassPatcher.patch(ClassLoaderDefineClassPatcher.java:93)
        at org.hotswap.agent.config.PluginManager.initClassLoader(PluginManager.java:186)
        - locked <0x00000000d98cd2a0> (a org.hotswap.agent.config.PluginManager)
        at org.hotswap.agent.util.HotswapTransformer$1.executeCommand(HotswapTransformer.java:316)
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
"main":
        at com.liubs.hotdeployseconds.server.HotSecondsTransformer.transform(HotSecondsTransformer.java:94)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        - locked <0x00000000c757d928> (a java.lang.Object)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.catalina.core.NamingContextListener.lifecycleEvent(NamingContextListener.java:231)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:771)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        - locked <0x00000000d9ec89c0> (a org.apache.catalina.core.StandardServer)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:695)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:347)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)

Found 1 deadlock.

**Comment by Liubsyy** [comment]
昨天晚上更新了HotSecondsServer-beat版本的包，你说的那两个问题应该都解决了，你再更新一下再试试
